### ISSUE TITLE
Transmission Result?

### ISSUE THREAD

**Issue by komplettsystem** [criteo/addressable-network-proposals#28]
https://github.com/criteo/addressable-network-proposals/blob/e131a358f40c4d4bb3e0ae863d2c3132fc6237bd/mvp-spec/dsp-api.md?plain=1#L203

Not quite sure I understand this part - isn't the transaction result what's coming back *from* the DSP and not what to expect in the transmission request? Also not sure I get the status or details described here.

**Comment by Sbenslimaneadanero** [comment]
Hi @RomainLofaso,
In step 8 "The DSP returns a Transmission Response 3 to the Transmission Request 3. It includes the Transmission Result 3. The 'children" field is empty." it should rather be "The DSP returns a Transmission Response 3 to the SSP2 right?
Also how is the Transmission Result 3 included as you are saying that the 'children' field is empty. In the case of Transmission Request, you modified in the #37 saying that the 'Parents' field include  "A list of Transmission Results that currently participate to a chain of Transmissions and make this Transmission possible.". Shouldn't be the same in this case as well and the 'children' should include the current list of Transmission results and so in the case of the Transmission Response sent by the DSP, this field is the one including the Transmission Result 3?

**Comment by RomainLofaso** [comment]
Hi @Sbenslimaneadanero ,

**Question about step 8**

Yes, it is the SSP2 because this is the SSP2 that sent the Transmission Request. I edited my message to add the Senders that receive the Transmission Response.

**Question about Transmission Result 3**

An example of Transmission Response would be:
```json
{
   "version":0,
   "transaction_id":1234567,
   "receiver":"dsp1.com",
   "status":"success",
   "details":"",
   "source":{
      "domain":"dsp1.com",
      "timestamp":1639589531,
      "signature":"12345_signature"
   },
   "children":[
      
   ]
}
```
Basically, it includes the Transaction Result and its children. Maybe the term "include" is misleading. Let me know.

**Question about Parents vs Children**

Sorry, I am not sure that I understood your question. The `children` field must include the list of Transmissions Results that participated to a potential generation of an Addressable Content. 


**Update of the document with the steps**
Here is an update to clarify this in both `audit-log-requirements.md` and `dps-api.md`.
https://github.com/criteo/addressable-network-proposals/pull/45


Let me know if it fits you and if I answered to your questions.
