### ISSUE TITLE
Publisher or SSP initiating the transmission request?

### ISSUE THREAD

**Issue by Sbenslimaneadanero** [criteo/addressable-network-proposals#38]
https://github.com/criteo/addressable-network-proposals/blob/d0c18b9a4c5b516ddb7d215b6a44a40ac78f3444/mvp-spec/landscape.md?plain=1#L90

My understanding is that the first transmission is coming from the publisher or the ad server on behalf of the publisher, right? @RomainLofaso could you please confirm?

**Comment by OlivierChirouze** [comment]
Yes, you are correct.
> The SSP receives a seed and transaction from the publisher and initiates (signed) transmissions to DSPs.

Is it confusing? Should I rephrase?
What about:
> The SSP receives a seed and **the first transmission from the publisher or its ad server** and initiates new (signed) transmissions to DSPs.

**Comment by RomainLofaso** [comment]
Hi,

The first transmission can come from the Publisher or the Ad Server. However, we can consider the Ad Server as part of an SSP in some setups, can we?

If so, I am wondering if we should stay abstract and rely on the decryption of the Prebid SSO Cookies to define who does the first Transmission. Concretely, the first/root Transmission comes from the Contracting Party that decrypts the Prebid SSO Cookies because plain Prebid SSO Data can be shared only via a Transmission. Therefore, this party needs to generate a Seed and Transmissions for sharing it with other parties.

So maybe I would update it in this way:

> The SSP shares Prebid SSO Data to DSPs via Transmission Requests. Depending of the context, it can generate the Seed and emit the first Transmission of the Transaction or receive the Seed from a previous Transmission Request.

What do you think ?

**Comment by Sbenslimaneadanero** [comment]
I agree with your proposal Romain, it's clearer. No matter who is generating the seed, it will be transmitted within the first transmission of the transaction.

**Comment by RomainLofaso** [comment]
Here is the change: https://github.com/criteo/addressable-network-proposals/pull/47
