### ISSUE TITLE
Returning url

### ISSUE THREAD

**Issue by Sbenslimaneadanero** [criteo/addressable-network-proposals#40]
https://github.com/criteo/addressable-network-proposals/blob/d0c18b9a4c5b516ddb7d215b6a44a40ac78f3444/mvp-spec/operator-design.md?plain=1#L85

Why the CMP is stepping in at this stage? Why is the CMP providing the returning URL and not the Publisher directly?

**Comment by OlivierChirouze** [comment]
Another "not-so-clear" part of the diagram, I must admit. Thanks for pointing it out.

Actually, the publisher itself provides its return URL when calling the CMP, via what I called the `pubPage` parameter.
I invented this keyword to emphasise that the publisher calls the CMP backend but doesn't have to know that behind the scenes, it's PAF that is called. That's why I didn't want to use the same name that is used when the CMP builds the URL to call on the operator.
But what really happens is: CMP takes the value of `pubPage` and puts it in `returnURL`.

So I realize it's just creating confusion. I will update the diagram to use `returnURL` at both steps.

To answer more broadly to your question, the reason why the CMP is stepping in is to **sign the request that will be sent to the operator**. This has to be done by a backend that (securely) owns a private key. It cannot be done by the frontend (in a browser).

Note that it doesn't have to be the CMP that signs, it just needs to be what I called an "operator backend proxy" (see https://github.com/criteo/addressable-network-proposals/blob/main/mvp-spec/landscape.md for a bit more context and https://github.com/criteo/addressable-network-proposals/blob/b17ee292010e4e29055854b0ee7b6a784291264c/mvp-spec/website-design.md for more details). In this example, this component is hosted by a CMP backend.

**Comment by Sbenslimaneadanero** [comment]
So if I understand it well, in this case we decided to make the CMP backend play the role of "operator backend proxy" but we could have chosen the publisher backend instead, right?
FYI I'm still not able to see the diagram  (it appears blank) https://github.com/criteo/addressable-network-proposals/blob/b17ee292010e4e29055854b0ee7b6a784291264c/mvp-spec/website-design.md whereas for the rest of mermaid diagrams I have no problem (after a refresh usually)

**Comment by OlivierChirouze** [comment]
>  in this case we decided to make the CMP backend play the role of "operator backend proxy" but we could have chosen the publisher backend instead
Precisely.

For the issue with Mermaid, we'll investigate together.
Anyway at some point we want to have these diagrams to be automatically generated, I will create an issue for that.
